### ISSUE TITLE
Some validation is not happening.

### ISSUE THREAD

**Issue by StefanoChiodino** [umco/umbraco-doc-type-grid-editor#114]
Hi there,

I'm running DTGE v0.5.0 on Umbraco v7.12.2. Validation doesn't seem to be happening for certain types. E.g. if I set textareas and dropdowns as mandatory they appear as such in the panel (a red `*`) but I can happily save it without selecting anything. In other cases like textboxes it works just fine.

![image](https://user-images.githubusercontent.com/1428893/45497220-297b4f00-b76f-11e8-8882-7ef6d8d733ae.png)

**Comment by leekelleher** [comment]
@StefanoChiodino Thanks for raising this, (sorry we hadn't replied sooner).  It's been quite a while since I've looked at how the validation works for DTGE, I'm not too sure how much control we have over it - there's definitely no server-side validation happening, only client-side.

If you (or anyone else) has any ideas & suggestions on how to implement better validation, we're totally open for help here.

**Comment by StefanoChiodino** [comment]
@leekelleher thanks for coming back to me.

Do you think that the client side validation works? Because it doesn't seems to me! Beside the red `*` nothing happens for me!

Unfortunately I don't know that much about DTGE or just Umbraco validation. However, I'd hope that there is a relatively easy way to validate each data type.

**Comment by leekelleher** [comment]
Closing off this ticket, (house keeping), as I haven't been able to get any further to figuring out how to trigger the validation in the overlay.

Happy to re-open if a community member can offer a PR.

**Comment by StefanoChiodino** [comment]
@leekelleher are we saying this is still a problem or not? I'm unsure on why this is being closed.

Cheers

**Comment by mattbrailsford** [comment]
Ok, just to add my 2 cents to this. The reason for closing is because it's not a simple fix and anything we code would be somewhat of a hack. The issue here is that client side validation can occur, however SERVER SIDE VALIDATION CAN NOT. In your scenario, the textbox renders a `required` attribute to the textbox and so this triggers client side validation for the textbox when the dialog is being submitted. The dropdown on the other hand, it's mandatory validation occurs server side which means we can't trigger it at the point of dialog submit. 

Now, there are 2 reasons why server side valdiation isn't possible.

1. The main server side validation is triggered only when the entire page is submitted to be saved, and at this point, the dialog is already closed and so we can't notify you of the invalid field anymore.
2. DTGE exists inside the grid and unfortunately the grids saving mechanism isn't built to propogate it's validation logic down through to DTGE at point of save so in this regard, DTGE isn't even asked to validate (this is outside our control)

With this, our stance simply has to be that validation is not truly supported in DTGE, and the effort to us would far outway it's usefulness. Our suggested solution is that you instead make everything non-mandatory and code your views defensively such that you don't display any items that do not have the required content. It's not an ideal solution, but it's the simplest.

As @leekelleher says though, we are happy for someone to look at it for a PR if they have an alternative, non hacky approach.

**Comment by StefanoChiodino** [comment]
Thanks Matt 👍
