### ISSUE TITLE
Implement caching of editors

### ISSUE THREAD

**Issue by skttl** [umco/umbraco-doc-type-grid-editor#119]
LeBlender has a way of easily enabling caching of specific editors, by setting a config value of the cache periode.

How about adding some config values for enabling caching of DTGE's?

Like (with default values)
```
"cachedSeconds": 0,
"cacheByPage": false,
"cacheByMember": false,
"cacheByContent": false
```

If cachedSeconds is set to more than zero, the output should be cached.

cacheByPage and cacheByMember is the equivalent of the properties on Html.CachedPartial() from Umbraco. (https://our.umbraco.com/documentation/reference/templating/mvc/partial-views#caching)

cacheByContent would use the contextualKeyBuilder and set the key to a serialized version of the editor value.

**Comment by skttl** [comment]
On a second thought, `cachebyContent` wouldn't be necessary as the cache is being rebuilt every time the content changes :)

**Comment by leekelleher** [comment]
Thanks for the suggestion @skttl. 👍
I haven't given it much thought yet, but didn't want to ignore you either 😃 

I'm not sure if `cacheByMember` is relevant either.  I guess `cacheByPage` would always be true? as the DTGE cell would be unique on a page - as in they are given a unique key (Guid).

Were you thinking that we could use `Html.CachedPartial` for this? My recollection is that it only works when `debug=false` (in Web.config). Otherwise we'd need to roll our own - which is fine, just means that we'd need to find a way to invalidate the cache too.

We'll give it some more thought, that was just my initial feedback.

**Comment by skttl** [comment]
I was thinking `Html.CachedPartial`

Over the weekend I played around with my grid rendering, and thought about having it as a Grid feature instead, in case I would want to use custom non-DTGE editors, like macro (which obviously is cacheable already 🤦‍♂️ ) or the forms editor.

So I might go that route instead.

**Comment by leekelleher** [comment]
@skttl What did you end up doing for this? Is it more a Grid feature or DTGE?

**Comment by skttl** [comment]
I think it should be more a grid feature than DTGE - at least that's how I ended up implementing :)

**Comment by mattbrailsford** [comment]
Late to the game, but my 2 cents. If it's needed outside of DTGE then it sounds like a core grid feature request. If you need it in DTGE, then much like "Toggle Gate" with Nested Content, I think this can be achieved by having a cache option on the DTGE config and then using Html.CachedPartial to handle the caching. Ultimately, I don't think it needs to be a "baked in" DTGE feature.

**Comment by skttl** [comment]
Agree - was the same considerations I had

**Comment by leekelleher** [comment]
OK cool. I'll close this ticket off. Thanks all!
