### ISSUE TITLE
Why are content tabs not rendered as tabs

### ISSUE THREAD

**Issue by frederikreher** [umco/umbraco-doc-type-grid-editor#120]
Is there any particular reason that the editor dialog is not similar to the dialog of stacked content? 
In the stacked content dialog the tabs of the document type is actually rendered as tabs - whereas the dtge dialog renders the properties of the the document type in one page.

**Comment by mattbrailsford** [comment]
It's mostly because DTGE came way before SC and so we learnt a lot since then :)

In addition, DTGE was written at a time when a lot of the UI hadn't yet been componentised so wasn't as easy to reuse as it is now. SC being newer, we were able to take advantage of these, but DTGE was before that time.

**Comment by frederikreher** [comment]
@mattbrailsford  Thank you for the prompt reply - maybe i'll take a look and see how easy the DTGE can be adapted to use the same dialog as SC :-)
