### ISSUE TITLE
Support for Umbraco v8

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-doc-type-grid-editor#130]
> **This is a placeholder issue to outline our intentions for DTGE support on Umbraco v8.**

### Latest update - 17<sup>th</sup> July 2019

 As it turns out, there is a significant demand for DTGE support in v8, a _work-in-progress_ pull-request has been started, see #137 for details.

DTGE support for Umbraco v8 is nearly complete. See PR #137 for history and details!

A huge thank you to @skttl for all his hard work on this. Also thank you to @bjarnef, @nul800sebastiaan, @ArnoldV, @cleversolutions and @recyclethis for your contributions and encouragement to move DTGE forwards.

The next step is to transfer ownership of DTGE over to @skttl.
We have outlined our migration plan on issue #146.

**Comment by mattbrailsford** [comment]
Just to add my 2 cents, and continuing from my comments on #126, my understanding is that in v8 there will be a new Grid that makes DTGE redundant (in the new grid, all cells are backed by Doc Types and the Grid is strongly typed). As mentioned in #126, this does not not currently look like it will be part of the initial v8 release, however the fact it is planned, I think any offorts should be spent helping getting the v8 Grid up to speed, rather than porting DTGE over to v8. </2-cents>

**Comment by leekelleher** [comment]
![dtge-y-u-no-v8](https://user-images.githubusercontent.com/209066/53420248-56e14f80-39d3-11e9-9c1c-3ce426601d7b.jpg)

**Comment by leekelleher** [comment]
Closing this ticket. A migration plan is in progress, see #146 for details.
