### ISSUE TITLE
Make the Guid `Key` accessible for grid-cell's `IPublishedContent`

### ISSUE THREAD

**Issue by bielu** [umco/umbraco-doc-type-grid-editor#131]
Hi,
As I need to make an identifier for every element from DTGE, I need some unique value (GUID) for every grid editor. For now, I solved that problem by change source of the package and propagate key of editor via version field for Ipublishedcontent.
Best Regards,
Arkadiusz Biel

**Comment by leekelleher** [comment]
Hi @bielu, would you be able to share the changes that you made to the DTGE source?

I'm curious about how the `IPublishedContent.Version` value ties to a DTGE grid-cell in the back-office.

**Comment by bielu** [comment]
Hi @leekelleher,
sure here is my code:
https://github.com/bielu/umbraco-doc-type-grid-editor
like you could see I make little cheating on that. :)

**Comment by leekelleher** [comment]
Hi @bielu, OK, I see what you are trying to do, by making the "key" value accessible in the `IPublishedContent`.  There might be a better way to achieve this, if we inherit from the [`PublishedContentWithKeyBase`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Models/PublishedContentWithKeyBase.cs) class instead.  I'll have a think about it.

**Comment by leekelleher** [comment]
I've added the `Key` property in to the content model, (in commit e7574f83ef0e8ee362c6edf3e24d83bf218d307f). One point to note is that the `Key` property isn't available on the standard `IPublishedContent`, you would need to use the `.GetKey()` extension method, (otherwise you'll need to cast the object to be `IPublishedContentWithKey` first).

This will be available in the next release of DTGE (v0.6.2), but I haven't scheduled a date yet.

**Comment by bielu** [comment]
@leekelleher  thanks I just pull your newest code works perfectly fine for me! :)
