### ISSUE TITLE
DTGE caused closing overlays on enter and Escape keys

### ISSUE THREAD

**Issue by bielu** [umco/umbraco-doc-type-grid-editor#132]
As we trying using tags inside of our DTGE we notice the problem with handling enter and escape key.  Steps to reproduce:
1) Click on any type of content, to open overlay
2) start writing something in the editor
3) Click Enter 
4) be kick out from overlay back to content
I think it is annoying for a user in case of handling tags in Doctype Grid Editor :) 
Many thanks!

**Comment by leekelleher** [comment]
Thanks for raising this @bielu.  It looks like the same issue raised in #95.  Since we're re-using Umbraco's overlay directive, the fix for this belongs in Umbraco itself, (either in the overlay or Tags editor).

Also it's worth noting that the Tags editor isn't supported within DTGE, (see our [known issues](https://github.com/umco/umbraco-doc-type-grid-editor#known-issues) for other unsupported editors). The reason being that Tags is designed to work at page-level, with additional data being written to the database associating tags with the page ID.
