### ISSUE TITLE
Unable to set the name of a Doc Type added and IPublishedContent.Id is always 0

### ISSUE THREAD

**Issue by John-Blair** [umco/umbraco-doc-type-grid-editor#139]
Great package - thanks.

I had hoped to reuse my document types and their current views unchanged in the grid layout via the Doc Type Editor.  I ran into 2 problems - my view was rendering the doctype.name property but this is always set to "doc type" now ..so i have to create a new doc type property to work around this.
The other problem was I was using the doctype "Id" property for a unique id on rendered html - but this is now always 0 for all doc types rendered. I can work around this with a unique id generator. I guess the doc types are not actually being stored as umbraco nodes so these issues may be "features".

**Comment by leekelleher** [comment]
@John-Blair Thanks for getting in touch!

1. The `Name` value its take from the Grid Editor itself, which is whatever is set for the entry in the "config/grid.editors.config.js" file, which out the box (for DTGE) is named "Doc Type". You can change that, or add other entries to the "grid.editors.config.js" file, (note, if the `allowedDocTypes` option matches a single DocType, then that's what will be used (automatically).

Failing that, you could look at the `nameTemplate` option, [it's referenced in the docs here](https://github.com/umco/umbraco-doc-type-grid-editor/blob/master/docs/developers-guide.md#example) - but we are missing documentation on how it works explicitly.  From what I recall, it uses AngularJs expressions, e.g. `"{{propertyAliasFromYourDocType}}"`.

2. The `Id` property, this is intentionally set to `0`, as like you say these aren't "real" nodes, DTGE fakes them.  DTGE does set the `Key` property with a GUID, that could be used instead? (Although keep in mind that `IPublishedContent` doesn't have a `Key` property, (because that interface pre-dates its existence), so you'll need to call `.GetKey()` extension method to get the GUID value.

I hope all this helps.

**Comment by John-Blair** [comment]
Thanks for the very quick reply - appreciate the suggestions.


  1.   I have multiple doc types in the grid layout so found it more convenient to add a Title property as I want the user to be able to set it.
  2.   The Id property: You might be surprised to hear but this broke all my custom controls (tabs, accordions, carousels etc) as these are all doc types and I was using the node id for id and href attribute use. Thanks for your suggestion. In the end I decided to go with creating a UniqueId extension method for general use in my controls. FYI I made the UniqueId a long (instead of an int) and starting above max int so as not to  conflict with any possible umbraco node.  Code below in case anyone else hits this problem and wants a solution.

With the above changes I can now use the doc types and views either inside the grid layout or standalone with the same results.


namespace Ec.UmbracoExtensions
{
    public static class ValueTypeExtensions
    {

        // Some packages store document types without a node id - return 0.
        // Generate a "unique id" for use in html id attributes.
        // Using above max int as the starting point as this will not clash with any existing umbraco node id.
        private const long _longSeed = ((long) int.MaxValue) + 1;
        private static long _nextUniqueNodeId = _longSeed;

        // Make access thread safe.
        internal static readonly object idlock = new object();

        internal static long NextUniqueNodeId
        {
            get
            {
                lock (idlock)
                {
                    if (_nextUniqueNodeId == long.MaxValue)
                    {
                        // Reset seed.
                        _nextUniqueNodeId = _longSeed;
                    }

                    return _nextUniqueNodeId++;
                }

            }
        }

        public static long UniqueId<T> (this T id) where T : struct  {

            return NextUniqueNodeId;

        }

        // Get a unique block of ids for use in HTML controls for use in id and href synchronisation.
        // Just return the first of those ids - knowing the following sequential ids are reserved.
        public static long UniqueIdRange<T>(this T id, int rangeSize = 1) where T : struct
        {
            // Reserve a range of node ids in thread safe manner.
            // Note: Keep ids sequential even if mid range hits the max long id by resetting the starting id to the seed.
            lock (idlock)
            {
                // Handle wrap of ids early to keep ids sequential.
                if ( long.MaxValue - rangeSize < _nextUniqueNodeId) _nextUniqueNodeId = _longSeed;

                long result = _nextUniqueNodeId;
                _nextUniqueNodeId += rangeSize;

                return result;
            }
        }

    }
}



Thanks

John Blair

________________________________

**Comment by leekelleher** [comment]
Hi @John-Blair, I'm curious. When you say "custom controls", are you meaning that these were pre-built before using DTGE? I'm not sure why I have this impression that they are .NET Server Controls? _But (hopefully) they are Razor partial-views?_ Like I say, I'm purely curious. 🙂

Maybe `.GetHashCode()` on the object might be unique enough? Save you the extra code. Anyway, you've written your code now and if it's working, all good. Cheers!

**Comment by John-Blair** [comment]
Hi Lee,

Yes, they are razor partial views (old naming habit from my earlier days of developing .net server controls).
I had developed these partial views before using the DTGE - so i just configured DTGE to point to the partial view directory and none of them worked initially due to the "id" = 0 issue.
I had considered .GetHashCode - but as this is only an "int" there is a chance this could return an existing umbraco node id - and i didn't want the possibility of clashing with any other 3rd party products where the node id was being used by their "controls" in the "id" attribute of the HTML - hence my use of a "long" starting at max int +1 and no possibility of collision (unless another developer has the same idea 🙂)

FYI The DTGE is a fantastic product and I was delighted at how little I had to change to now have all my "controls" - including multiple instances -  working in any grid layout!

Suggestion: W.r.t. DTGE, I would consider storing the instances of the doc types as actual umbraco nodes so they behave exactly like content nodes created from doc types, where Id and name properties could be set and available per usual use.
If that was not feasibly, another thing i'd consider is to add a "long UniqueId or GUID" to the Properties collection of the IPublishedContent object returned from DTGE - again as they are "fake" nodes I'd mandate the type as long or GUID instead of int. This would be useful for anyone else who experienced my issue. I'm curious if i am the only one experiencing an issue with id - maybe other partial view developers have a better way of generating unique "id" values in the html!



Thanks

John Blair

________________________________

**Comment by leekelleher** [comment]
Hi @John-Blair, I mentioned in my initial reply that each item has a GUID set, you can get the value using `.GetKey()`.

re: using "real nodes", yup **we'd love that too!** It's something we considered when we started development on DTGE. It introduced many complications, in terms of performance and structure, e.g. where would these nodes live in the tree? We had many discussions with Umbraco core team about it.

Ultimately, DTGE is a hack (in a non-offensive way), in order to re-use Doc Types for smaller fragmented content items.

Hopefully one day, this approach may influence Umbraco core to adopt a similar concept. 😃

**Comment by John-Blair** [comment]
Hi Lee, Yes I agree - one for the umbraco team to adopt.

FYI I'd put the nodes in the Settings/Content Templates area of the tree.

[cid:7f813cd3-503b-4efc-8f29-975cd9eb9775]



Thanks

John Blair

________________________________
