### ISSUE TITLE
Improve the Preview mechanism

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-doc-type-grid-editor#59]
Explore a way to improve the Preview mechanism, so we can handle content that is published/unpublished and/or has an assigned template.

**Comment by leekelleher** [comment]
The previewer in [Stacked Content](https://github.com/umco/umbraco-stacked-content) feels like a much better fit, we should backport it to DTGE // @mattbrailsford

**Comment by alindgren** [comment]
Preview is not working for me on a site that has a custom content finder. It  is returning a 404 when trying to access the preview. Would be nice to have this not depend on that - maybe a back-end controller that renders the view?

**Comment by jfsaliba** [comment]
Just a thought, having run into backoffice previews returning 404s today. I don't want to disable "disableFindContentByIdPath" in umbracoSettings.config because I want to lock down public URLs and limit any probing/URL enumeration attack vectors (however minimal). But the DTGE preview depends entirely on this setting (POSTing to /[id]?dtgePreview=1 to render the preview).

My workaround is to register a custom ContentFinder in Umbraco that matches that preview URL and *only* runs for authorized Umbraco backoffice users (I have a helper method that verifies that using GetUmbracoAuthTicket(), got the idea from the Our forums). On matches, it just takes the node ID from the matched URL, gets the IPublishedContent item for it, and sets contentRequest.PublishedContent to that item.

Of course, a backoffice preview method that doesn't depend on disabling disableFindContentByIdPath would be way better, but I'm offering my general solution in case it helps others in the meantime.

**Comment by leekelleher** [comment]
@jfsaliba Thanks for letting us know about your workaround solution 👍 
A pull request, #105, has been proposed, which I'll review soon - I'm hoping this will rectify these issues.

**Comment by leekelleher** [comment]
Closing this ticket, the approach in PR #105 is what we're going with.
