### ISSUE TITLE
RTE buttons not working

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-doc-type-grid-editor#80]
> **Issue copied over from Our Umbraco**...
> <https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/88121-panels-not-opening-properly>

I've cross posted this from the "extending backoffice" category as I didn't realize there was a DTGE feedback section.

I have Doctype Grid Editor installed and many of my doctypes that are being used in the grid include rich text editors. The problem I am having is that when I click any button in the RTE that should open a panel (like the media picker) nothing happens.

The other odd thing is that I can get the panels to open by clicking first on the button, then somewhere within the RTE area, then somewhere outside of the RTE. (see image below)

![screengrab](https://our.umbraco.org/media/upload/0fd4c990-ce69-4d76-b021-1847d766d17f/Capture.PNG)

Here's some extra info:

1. There are no console errors when I click on the RTE buttons
2. This problem is only present in RTE's which are in the DocType Grid Editor panel (see image above), it is not a problem in RTE's which are simply in a page doctype or even within the default Umbraco grid.
3. There are no errors in UmbracoTraceLog

Any ideas?? Thanks in advance!

**Comment by mykebates** [comment]
Just wanted to chime in here and maybe gain some focus. For me, the buttons DO respond, but it takes an extremely long time. Like 15-20 seconds kind of long time. Wondering if anyone else can corroborate this, or if it's isolated to my setup.

**Comment by MrCosmo** [comment]
@mykebates Seems like all older comments are gone but yes, more people has this issue. Including me. As far as I'm aware of there is no fix yet.

**Comment by hallojoe** [comment]
We have the same problem as we speak. 

When clicking insert image button then nothing happens...then clicking ANY other button, will open the dialog and an image can be selected. 

I get no console error or warning  i chrome, but in firefox i get: Empty string passed to getElementById() as a warning.

**Comment by danbramall** [comment]
On what versions of Umbraco/DTGE are people seeing this?  I can reproduce it in Umbraco 7.7.7 and 7.7.8 using DTGE 0.4.0, but have an old site running Umbraco 7.5.6 and DTGE 0.3.0 in which it's not an issue.

For me the link picker does eventually open without intervention, but it is 15-20 seconds as per @mykebates  comment.  Otherwise you can click anywhere in the slide-out panel above the RTE after clicking the RTE link button and it opens straight away.

Gut feeling was that is is a CSS issue, but it seems much deeper than that since Angular isn't actually injecting the link panel mark-up until after the delay (or on clicking elsewhere).  A tricky one but if we can narrow down the CMS version particularly that would be helpful.

**Comment by mykebates** [comment]
7.6.4 is the version I was/am experiencing it on.

**Comment by MrCosmo** [comment]
7.7.6 for me

**Comment by thomashdk** [comment]
7.7.2 for me still an issue. link button only work if I click another button afterwards

**Comment by dawoe** [comment]
We seeing this to on newer versions of Umbraco.
Maybe this PR is the cause : https://github.com/umbraco/Umbraco-CMS/pull/1813

This was part of 7.6.0 release.

So if the issue is not present in 7.5.9 and it is in 7.6.0 this probably the cause. Maybe we can have @madsrasmussen shine a light on this ?

**Comment by dawoe** [comment]
I have been playing around with my local 7.7.9 install to see if I could fix this by using the new umb-overlay directive instead of the dialogservice to show the editing dialog.

The issue is not present then. Will try to make a PR soon.

It can be that this breaks all installations lower than v7.6. For sure it will not work in versions lower than 7.4 because the umb-overlay is added in that version.

Will see if I can build in a check for which versions and keep the old way of working in place

Dave

**Comment by leekelleher** [comment]
Thanks for looking into this @dawoe! 😎
Currently our minimum support is for Umbraco 7.3.0, but I'd be happy for that to be upgraded to v7.6 _(unless if anyone opposes that? Have your say now.)_

**Comment by dawoe** [comment]
Hi Lee,

I created a PR that fixes this. Unfortunately i started from master branch and not develop. So it's possible that some changes need to be added

Dave

**Comment by leekelleher** [comment]
Closing, fixed in #86
