### ISSUE TITLE
Edit pane stays empty in v7.8

### ISSUE THREAD

**Issue by dawoe** [umco/umbraco-doc-type-grid-editor#88]
When trying to use this package in v7.8 the edit pane stays empty

I see this console error : 
```
angular.min.js?cdv=2085597849:63 TypeError: mainTreeEventHandler.syncTree is not a function
    at Object.syncTree (umbraco.services.js?cdv=2085597849:5211)
    at umbraco.controllers.js?cdv=2085597849:8836
    at angular.min.js?cdv=2085597849:108
    at e (angular.min.js?cdv=2085597849:31)
    at angular.min.js?cdv=2085597849:34
```

**Comment by dawoe** [comment]
I created a PR for this one :  https://github.com/umco/umbraco-doc-type-grid-editor/pull/89

**Comment by markglibres** [comment]
hi @dawoe , found the same probem and fixed it as well on my local. however you might need to change the code to insert this line inside the loop instead of removing the pop.

 if (!data.tabs[t].active) { continue; }

uncommenting the existing code will get the properties tab for older version of Umbraco...

**Comment by mattbrailsford** [comment]
I've just commited a fix https://github.com/umco/umbraco-doc-type-grid-editor/commit/ac98e71c822e1ece0937b7a34c2efa550d6fd998 if you want to test the nightly being built atm, that would be great.

I implemented this fix in Innner Content already so just ported it over. Uses the same version checking method as used by umbraco forms so should be a bit more robust
